DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
	ID NUMBER NOT NULL AUTO_INCREMENT,
	FIRST_NAME NVARCHAR2(64) NOT NULL,
	LAST_NAME NVARCHAR2(64) NOT NULL,
	BIRTH_DATE DATE NOT NULL
);

ALTER TABLE STUDENT ADD CONSTRAINT PKC_STUDENT PRIMARY KEY (ID);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (
	ID NUMBER NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR2(128) NOT NULL,
	NAME NVARCHAR2(128) NOT NULL,
	DESCRIPTION CLOB
);

ALTER TABLE COURSE ADD CONSTRAINT PKC_COURSE PRIMARY KEY (ID);

DROP TABLE IF EXISTS ENROLLED;
CREATE TABLE ENROLLED (
	COURSE NUMBER NOT NULL,
	STUDENT NUMBER NOT NULL
);

ALTER TABLE ENROLLED ADD CONSTRAINT PKC_ENROLLED PRIMARY KEY (COURSE, STUDENT);

